/**
 * Medroute Healthcare Super-App - SINGLE MASTER DATA FILE
 * All application data lives here and nowhere else:
 * cities, hospitals, specialists, doctors, lab tests, medicines, surgeries,
 * gold plans, sample claims, AI symptom triage data, vaccination schedules,
 * and the default user/state store. Other modules read from this one file.
 */

const MEDROUTE_DATA = {
  // Punjab Healthcare Districts and Medical Hubs (Punjab Only)
  cities: [
    { id: 'ludhiana', name: 'Ludhiana', state: 'Punjab', pincodes: ['141001', '141002', '141003', '141008', '141010'] },
    { id: 'amritsar', name: 'Amritsar', state: 'Punjab', pincodes: ['143001', '143002', '143005', '143006', '143008'] },
    { id: 'jalandhar', name: 'Jalandhar', state: 'Punjab', pincodes: ['144001', '144002', '144003', '144008', '144022'] },
    { id: 'bathinda', name: 'Bathinda', state: 'Punjab', pincodes: ['151001', '151002', '151003', '151005', '151101'] },
    { id: 'mohali', name: 'Mohali (SAS Nagar)', state: 'Punjab', pincodes: ['160055', '160059', '160062', '160070', '160071'] },
    { id: 'patiala', name: 'Patiala', state: 'Punjab', pincodes: ['147001', '147002', '147003', '147004', '147101'] },
    { id: 'pathankot', name: 'Pathankot', state: 'Punjab', pincodes: ['145001', '145023', '145025'] },
    { id: 'hoshiarpur', name: 'Hoshiarpur', state: 'Punjab', pincodes: ['146001', '146023', '146111'] },
    { id: 'moga', name: 'Moga', state: 'Punjab', pincodes: ['142001', '142011', '142038'] },
    { id: 'barnala', name: 'Barnala', state: 'Punjab', pincodes: ['148101', '148105'] },
    { id: 'firozpur', name: 'Firozpur', state: 'Punjab', pincodes: ['152001', '152002', '152004'] },
    { id: 'faridkot', name: 'Faridkot', state: 'Punjab', pincodes: ['151203', '151212'] },
    { id: 'kapurthala', name: 'Kapurthala', state: 'Punjab', pincodes: ['144601', '144602', '144620'] },
    { id: 'malerkotla', name: 'Malerkotla', state: 'Punjab', pincodes: ['148023', '148025'] },
    { id: 'khanna', name: 'Khanna', state: 'Punjab', pincodes: ['141401', '141417'] },
    { id: 'mansa', name: 'Mansa', state: 'Punjab', pincodes: ['151505', '151508'] },
    { id: 'muktsar', name: 'Sri Muktsar Sahib', state: 'Punjab', pincodes: ['152026', '152032'] },
    { id: 'nawanshahr', name: 'Nawanshahr (SBS Nagar)', state: 'Punjab', pincodes: ['144514', '144517'] },
    { id: 'rupnagar', name: 'Rupnagar (Ropar)', state: 'Punjab', pincodes: ['140001', '140111'] },
    { id: 'sangrur', name: 'Sangrur', state: 'Punjab', pincodes: ['148001', '148024'] },
    { id: 'fazilka', name: 'Fazilka', state: 'Punjab', pincodes: ['152123', '152124'] },
    { id: 'abohar', name: 'Abohar', state: 'Punjab', pincodes: ['152116', '152117'] },
    { id: 'tarn-taran', name: 'Tarn Taran', state: 'Punjab', pincodes: ['143401', '143412'] },
    { id: 'gurdaspur', name: 'Gurdaspur', state: 'Punjab', pincodes: ['143521', '143531'] }
  ],

  // Genuine Empaneled Hospital Chains in Punjab
  hospitals: [
    {
      id: 'hosp-1',
      name: 'Christian Medical College & Hospital (CMC)',
      branch: 'Brown Road, Ludhiana',
      network: 'CMC Ludhiana Healthcare Society',
      city: 'ludhiana',
      pincode: '141008',
      address: 'Brown Road, Near Clock Tower, Ludhiana, Punjab 141008',
      accreditation: ['NABH', 'NABL', 'Ayushman Empaneled'],
      beds: 775,
      rating: 4.8,
      reviewsCount: 4120,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Vidal Health', 'Star Health', 'HDFC ERGO', 'ICICI Lombard', 'Care Health', 'Ayushman Bharat'],
      specialties: ['Cardiology', 'Orthopedics', 'Oncology', 'Neurology', 'Nephrology', 'Emergency & Trauma'],
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 161 2115000',
      receptionPhone: '+91 161 2115200',
      ambulancePhone: '+91 161 2115108',
      tpaDeskPhone: '+91 161 2115444',
      bloodBankPhone: '+91 161 2115120',
      category: 'Multi-Speciality Medical College',
      opdTimings: '24x7 Casualty • OPD 08:30 AM - 04:30 PM'
    },
    {
      id: 'hosp-2',
      name: 'Fortis Hospital Mohali',
      branch: 'Sector 62, Phase 8',
      network: 'Fortis Healthcare',
      city: 'mohali',
      pincode: '160062',
      address: 'Sector 62, Phase 8, Sahibzada Ajit Singh Nagar, Mohali, Punjab 160062',
      accreditation: ['JCI Accredited', 'NABH', 'NABL', 'Green OT'],
      beds: 355,
      rating: 4.9,
      reviewsCount: 5210,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Paramount TPA', 'Niva Bupa', 'HDFC ERGO', 'Aditya Birla', 'Star Health'],
      specialties: ['Organ Transplant', 'Cardiac Sciences', 'Neurosciences', 'Robotic Surgery', 'Oncology'],
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 172 4692222',
      receptionPhone: '+91 172 5061222',
      ambulancePhone: '+91 172 4692108',
      tpaDeskPhone: '+91 172 5061555',
      bloodBankPhone: '+91 172 5061333',
      category: 'Super-Speciality Corporate',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 06:00 PM'
    },
    {
      id: 'hosp-3',
      name: 'Dayanand Medical College & Hospital (DMCH)',
      branch: 'Tagore Nagar, Civil Lines',
      network: 'DMCH Managing Society',
      city: 'ludhiana',
      pincode: '141001',
      address: 'Tagore Nagar, Civil Lines, Ludhiana, Punjab 141001',
      accreditation: ['NABH', 'NABL', 'ISO 9001'],
      beds: 1325,
      rating: 4.8,
      reviewsCount: 6120,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Heritage Health', 'Bajaj Allianz', 'SBI General', 'United India'],
      specialties: ['Hero DMC Heart Institute', 'Gastroenterology', 'Trauma & Critical Care', 'Nephrology'],
      image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 161 4687700',
      receptionPhone: '+91 161 4688800',
      ambulancePhone: '+91 161 4687108',
      tpaDeskPhone: '+91 161 4688222',
      bloodBankPhone: '+91 161 4687333',
      category: 'Multi-Speciality & Cardiac Center',
      opdTimings: '24x7 Trauma • OPD 08:00 AM - 05:00 PM'
    },
    {
      id: 'hosp-4',
      name: 'Max Super Speciality Hospital Mohali',
      branch: 'Phase 6, Sector 56',
      network: 'Max Healthcare',
      city: 'mohali',
      pincode: '160055',
      address: 'Near Civil Hospital, Phase 6, Sector 56, Sahibzada Ajit Singh Nagar, Mohali, Punjab 160055',
      accreditation: ['NABH', 'NABL', 'JCI Accredited Standards'],
      beds: 230,
      rating: 4.8,
      reviewsCount: 3890,
      cashless: true,
      tpaPartners: ['Medi Assist', 'FHPL', 'Tata AIG', 'Care Health', 'ICICI Lombard', 'Star Health'],
      specialties: ['Minimal Access Surgery', 'Cardiology', 'Orthopedics', 'Urology', 'Cancer Care'],
      image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 172 6652000',
      receptionPhone: '+91 172 6652222',
      ambulancePhone: '+91 172 6652108',
      tpaDeskPhone: '+91 172 6652333',
      bloodBankPhone: '+91 172 6652444',
      category: 'Super-Speciality Oncology & Surgery',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 05:30 PM'
    },
    {
      id: 'hosp-5',
      name: 'Sri Guru Ram Das Institute of Medical Sciences (SGRD)',
      branch: 'Mehta Road, Vallah',
      network: 'SGRD Charitable Trust',
      city: 'amritsar',
      pincode: '143501',
      address: 'Mehta Road, Vallah, Amritsar, Punjab 143501',
      accreditation: ['NABH', 'NABL', 'Ayushman Bharat Certified'],
      beds: 1000,
      rating: 4.7,
      reviewsCount: 4780,
      cashless: true,
      tpaPartners: ['Medi Assist', 'MDIndia', 'Star Health', 'United India', 'New India', 'National Insurance'],
      specialties: ['Cancer Care & Radiotherapy', 'Neurosurgery', 'Cardiothoracic Surgery', 'Pediatrics'],
      image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 183 2870200',
      receptionPhone: '+91 183 2870300',
      ambulancePhone: '+91 183 2870108',
      tpaDeskPhone: '+91 183 2870400',
      bloodBankPhone: '+91 183 2870500',
      category: 'Medical College & Cancer Care',
      opdTimings: '24x7 Casualty • OPD 08:30 AM - 04:00 PM'
    },
    {
      id: 'hosp-6',
      name: 'Patel Hospital Jalandhar',
      branch: 'Civil Lines',
      network: 'Patel Healthcare',
      city: 'jalandhar',
      pincode: '144001',
      address: 'Civil Lines, Near BMC Chowk, Jalandhar, Punjab 144001',
      accreditation: ['NABH', 'NABL', 'Green OT'],
      beds: 250,
      rating: 4.9,
      reviewsCount: 2950,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Vidal Health', 'HDFC ERGO', 'ICICI Lombard', 'Star Health'],
      specialties: ['Surgical Oncology', 'Robotic Surgery', 'Urology', 'Gastroenterology'],
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 181 5241000',
      receptionPhone: '+91 181 5241200',
      ambulancePhone: '+91 181 5241108',
      tpaDeskPhone: '+91 181 5241300',
      bloodBankPhone: '+91 181 5241400',
      category: 'Surgical Oncology & Robotic Center',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 06:00 PM'
    },
    {
      id: 'hosp-7',
      name: 'Max Super Speciality Hospital Bathinda',
      branch: 'Civil Lines, Mansa Road',
      network: 'Max Healthcare',
      city: 'bathinda',
      pincode: '151001',
      address: 'NH-64, Near District Civil Hospital, Mansa Road, Bathinda, Punjab 151001',
      accreditation: ['NABH', 'NABL'],
      beds: 200,
      rating: 4.8,
      reviewsCount: 2600,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Star Health', 'United India', 'Care Health', 'Bajaj Allianz'],
      specialties: ['Comprehensive Cancer Care', 'Interventional Cardiology', 'Orthopedics & Joint Replacement', 'Neurosciences'],
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 164 6601234',
      receptionPhone: '+91 164 6601000',
      ambulancePhone: '+91 164 6601108',
      tpaDeskPhone: '+91 164 6601555',
      bloodBankPhone: '+91 164 6601333',
      category: 'Super-Speciality & Trauma Care',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 05:00 PM'
    },
    {
      id: 'hosp-8',
      name: 'Government Medical College & Rajindra Hospital',
      branch: 'Sangrur Road',
      network: 'Punjab Medical Education',
      city: 'patiala',
      pincode: '147001',
      address: 'Sangrur Road, New Lal Bagh Colony, Patiala, Punjab 147001',
      accreditation: ['Government Super Speciality', 'NABH', 'Ayushman Bharat'],
      beds: 1100,
      rating: 4.7,
      reviewsCount: 5200,
      cashless: true,
      tpaPartners: ['Ayushman Bharat PMJAY', 'Medi Assist', 'MDIndia', 'United India', 'Star Health'],
      specialties: ['Trauma Care', 'Cardiology & Cath Lab', 'Nephrology & Dialysis', 'Pediatrics & Neonatology'],
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 175 2212018',
      receptionPhone: '+91 175 2212000',
      ambulancePhone: '+91 175 2212108',
      tpaDeskPhone: '+91 175 2212444',
      bloodBankPhone: '+91 175 2212222',
      category: 'Government Medical College & Hospital',
      opdTimings: '24x7 Casualty • OPD 08:00 AM - 03:00 PM'
    },
    {
      id: 'hosp-9',
      name: 'Civil Hospital Ludhiana',
      branch: 'Jail Road, Field Ganj',
      network: 'Punjab Health Systems Corporation',
      city: 'ludhiana',
      pincode: '141008',
      address: 'Near Clock Tower, Jail Road, Field Ganj, Ludhiana, Punjab 141008',
      accreditation: ['Government District Hospital', 'Ayushman PMJAY Empaneled'],
      beds: 300,
      rating: 4.5,
      reviewsCount: 3100,
      cashless: true,
      tpaPartners: ['Ayushman Bharat PMJAY', 'Medi Assist', 'MDIndia', 'United India'],
      specialties: ['General Medicine', 'Trauma Care', 'Mother & Child Care', 'Orthopedics', 'Emergency'],
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 161 2444555',
      receptionPhone: '+91 161 2444550',
      ambulancePhone: '+91 161 2444108',
      tpaDeskPhone: '+91 161 2444777',
      bloodBankPhone: '+91 161 2444120',
      category: 'Government District Hospital',
      opdTimings: '24x7 Emergency • OPD 08:00 AM - 02:00 PM'
    },
    {
      id: 'hosp-10',
      name: 'Amandeep Hospital Amritsar',
      branch: 'Model Town, G.T. Road',
      network: 'Amandeep Healthcare Group',
      city: 'amritsar',
      pincode: '143001',
      address: 'Model Town, G.T. Road, Near Bus Stand, Amritsar, Punjab 143001',
      accreditation: ['NABH', 'NABL', 'Green OT'],
      beds: 200,
      rating: 4.8,
      reviewsCount: 3400,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Star Health', 'HDFC ERGO', 'ICICI Lombard', 'Ayushman Bharat'],
      specialties: ['Orthopedics & Joint Replacement', 'Plastic & Microvascular Surgery', 'Neurotrauma', 'Emergency'],
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 183 5051515',
      receptionPhone: '+91 183 2582200',
      ambulancePhone: '+91 183 5051108',
      tpaDeskPhone: '+91 183 5051400',
      bloodBankPhone: '+91 183 5051333',
      category: 'Orthopedics & Multi-Speciality',
      opdTimings: '24x7 Trauma • OPD 09:00 AM - 06:00 PM'
    },
    {
      id: 'hosp-11',
      name: 'Tagore Hospital & Heart Care Centre Jalandhar',
      branch: 'Mahavir Marg',
      network: 'Tagore Healthcare',
      city: 'jalandhar',
      pincode: '144008',
      address: 'Banda Bahadur Nagar, Mahavir Marg, Jalandhar, Punjab 144008',
      accreditation: ['NABH', 'NABL'],
      beds: 260,
      rating: 4.7,
      reviewsCount: 2850,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Vidal Health', 'Star Health', 'Bajaj Allianz', 'SBI General'],
      specialties: ['Cardiology & Cath Lab', 'Cardiothoracic Surgery', 'Nephrology & Dialysis', 'Critical Care'],
      image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 181 2603000',
      receptionPhone: '+91 181 2603100',
      ambulancePhone: '+91 181 2603108',
      tpaDeskPhone: '+91 181 2603400',
      bloodBankPhone: '+91 181 2603222',
      category: 'Cardiac & Multi-Speciality Institute',
      opdTimings: '24x7 Emergency • OPD 08:30 AM - 05:30 PM'
    },
    {
      id: 'hosp-12',
      name: 'Ivy Hospital Mohali',
      branch: 'Sector 71',
      network: 'Ivy Healthcare Network',
      city: 'mohali',
      pincode: '160071',
      address: 'Sector 71, Sahibzada Ajit Singh Nagar, Mohali, Punjab 160071',
      accreditation: ['NABH', 'NABL'],
      beds: 220,
      rating: 4.7,
      reviewsCount: 3900,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Paramount', 'Niva Bupa', 'HDFC ERGO', 'Star Health'],
      specialties: ['Oncology & Chemotherapy', 'Nephrology & Kidney Transplant', 'Neurosciences', 'Cardiology'],
      image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 172 7170000',
      receptionPhone: '+91 172 7170100',
      ambulancePhone: '+91 172 7170108',
      tpaDeskPhone: '+91 172 7170300',
      bloodBankPhone: '+91 172 7170222',
      category: 'Super-Speciality Corporate',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 06:00 PM'
    },
    {
      id: 'hosp-13',
      name: 'Guru Gobind Singh Medical College & Hospital (GGSMCH)',
      branch: 'Sadiq Road',
      network: 'Baba Farid University of Health Sciences',
      city: 'faridkot',
      pincode: '151203',
      address: 'Sadiq Road, Faridkot, Punjab 151203',
      accreditation: ['Government Medical College', 'NABH', 'Ayushman Bharat'],
      beds: 850,
      rating: 4.6,
      reviewsCount: 4100,
      cashless: true,
      tpaPartners: ['Ayushman Bharat PMJAY', 'MDIndia', 'United India', 'Medi Assist'],
      specialties: ['Comprehensive Cancer Center', 'Trauma & Emergency', 'Cardiology', 'Pediatrics & NICU'],
      image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 1639 251111',
      receptionPhone: '+91 1639 250000',
      ambulancePhone: '+91 1639 251108',
      tpaDeskPhone: '+91 1639 251444',
      bloodBankPhone: '+91 1639 251222',
      category: 'Government Medical College & Hospital',
      opdTimings: '24x7 Casualty • OPD 08:00 AM - 02:00 PM'
    },
    {
      id: 'hosp-14',
      name: 'Adesh Institute of Medical Sciences & Research',
      branch: 'NH-7, Barnala Road',
      network: 'Adesh University',
      city: 'bathinda',
      pincode: '151101',
      address: 'NH-7, Barnala Road, Bhucho Mandi, Bathinda, Punjab 151101',
      accreditation: ['NABH', 'NABL', 'Ayushman Empaneled'],
      beds: 750,
      rating: 4.7,
      reviewsCount: 3200,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Star Health', 'Care Health', 'Ayushman Bharat PMJAY'],
      specialties: ['Cancer Institute', 'Cardiology', 'Orthopedics', 'General Surgery', 'Obstetrics & Gynae'],
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 164 5252000',
      receptionPhone: '+91 164 5252100',
      ambulancePhone: '+91 164 5252108',
      tpaDeskPhone: '+91 164 5252300',
      bloodBankPhone: '+91 164 5252222',
      category: 'Multi-Speciality Medical University Hospital',
      opdTimings: '24x7 Emergency • OPD 08:30 AM - 04:30 PM'
    },
    {
      id: 'hosp-15',
      name: 'Apex Hospital & Trauma Centre Pathankot',
      branch: 'Dhangu Road',
      network: 'Apex Healthcare Pathankot',
      city: 'pathankot',
      pincode: '145001',
      address: 'Dhangu Road, Near Bus Stand, Pathankot, Punjab 145001',
      accreditation: ['NABH Certified', 'Ayushman Empaneled'],
      beds: 150,
      rating: 4.6,
      reviewsCount: 1800,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Star Health', 'HDFC ERGO', 'Ayushman Bharat'],
      specialties: ['24x7 Trauma & Casualty', 'Spine & Joint Surgery', 'Critical Care & ICU', 'General Medicine'],
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 186 2228000',
      receptionPhone: '+91 186 2228100',
      ambulancePhone: '+91 186 2228108',
      tpaDeskPhone: '+91 186 2228300',
      bloodBankPhone: '+91 186 2228222',
      category: 'Trauma & Emergency Care',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 05:00 PM'
    },
    {
      id: 'hosp-16',
      name: 'Shivam Hospital & Heart Centre Hoshiarpur',
      branch: 'Mall Road, Civil Lines',
      network: 'Shivam Healthcare',
      city: 'hoshiarpur',
      pincode: '146001',
      address: 'Mall Road, Civil Lines, Hoshiarpur, Punjab 146001',
      accreditation: ['NABH Certified', 'Ayushman Empaneled'],
      beds: 120,
      rating: 4.6,
      reviewsCount: 1650,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Star Health', 'United India', 'SBI General'],
      specialties: ['Interventional Cardiology', 'Cardiac ICU', 'General Medicine', 'Diabetology'],
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 1882 225000',
      receptionPhone: '+91 1882 225100',
      ambulancePhone: '+91 1882 225108',
      tpaDeskPhone: '+91 1882 225300',
      bloodBankPhone: '+91 1882 225222',
      category: 'Cardiology & Intensive Care',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 06:00 PM'
    },
    {
      id: 'hosp-17',
      name: 'Medicity Hospital Moga',
      branch: 'GT Road',
      network: 'Medicity Healthcare Moga',
      city: 'moga',
      pincode: '142001',
      address: 'GT Road, Near Nature Park, Moga, Punjab 142001',
      accreditation: ['NABH', 'Ayushman Empaneled'],
      beds: 140,
      rating: 4.7,
      reviewsCount: 1950,
      cashless: true,
      tpaPartners: ['Medi Assist', 'HDFC ERGO', 'Care Health', 'Star Health', 'Ayushman Bharat'],
      specialties: ['Critical Care ICU', 'Laparoscopic Surgery', 'Orthopedics & Joint Care', 'Pediatrics'],
      image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 1636 228000',
      receptionPhone: '+91 1636 228100',
      ambulancePhone: '+91 1636 228108',
      tpaDeskPhone: '+91 1636 228300',
      bloodBankPhone: '+91 1636 228222',
      category: 'Multi-Speciality & Critical Care',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 05:30 PM'
    },
    {
      id: 'hosp-18',
      name: 'Sanjeevani Super Speciality Hospital Barnala',
      branch: 'College Road',
      network: 'Sanjeevani Healthcare',
      city: 'barnala',
      pincode: '148101',
      address: 'College Road, Near ITI Chowk, Barnala, Punjab 148101',
      accreditation: ['NABH Certified', 'Ayushman Empaneled'],
      beds: 110,
      rating: 4.5,
      reviewsCount: 1420,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Star Health', 'United India', 'Ayushman Bharat PMJAY'],
      specialties: ['General Surgery', 'Orthopedics', 'Urology', 'Internal Medicine'],
      image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 1679 235000',
      receptionPhone: '+91 1679 235100',
      ambulancePhone: '+91 1679 235108',
      tpaDeskPhone: '+91 1679 235300',
      bloodBankPhone: '+91 1679 235222',
      category: 'Multi-Speciality Surgical Center',
      opdTimings: '24x7 Emergency • OPD 09:00 AM - 05:00 PM'
    },
    {
      id: 'hosp-19',
      name: 'Anil Baghi Hospital Firozpur',
      branch: 'Baghi Hospital Road',
      network: 'Anil Baghi Healthcare Trust',
      city: 'firozpur',
      pincode: '152002',
      address: 'Ferozepur City, Near Baghi Hospital Road, Firozpur, Punjab 152002',
      accreditation: ['NABH', 'NABL', 'Ayushman Empaneled'],
      beds: 150,
      rating: 4.7,
      reviewsCount: 2200,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Star Health', 'ICICI Lombard', 'HDFC ERGO', 'Ayushman Bharat'],
      specialties: ['Interventional Cardiology & Cath Lab', 'Joint Replacement', 'Gastroenterology', 'Dialysis'],
      image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 1632 245000',
      receptionPhone: '+91 1632 245100',
      ambulancePhone: '+91 1632 245108',
      tpaDeskPhone: '+91 1632 245300',
      bloodBankPhone: '+91 1632 245222',
      category: 'Multi-Speciality & Trauma Hospital',
      opdTimings: '24x7 Emergency • OPD 08:30 AM - 05:00 PM'
    },
    {
      id: 'hosp-20',
      name: 'Satguru Partap Singh (SPS) Hospital Ludhiana',
      branch: 'Sherpur Chowk, G.T. Road',
      network: 'SPS Hospitals (Formerly Apollo)',
      city: 'ludhiana',
      pincode: '141003',
      address: 'Sherpur Chowk, G.T. Road, Ludhiana, Punjab 141003',
      accreditation: ['JCI Accredited', 'NABH', 'NABL'],
      beds: 350,
      rating: 4.9,
      reviewsCount: 5400,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Vidal Health', 'Star Health', 'Niva Bupa', 'HDFC ERGO', 'ICICI Lombard'],
      specialties: ['Organ Transplant (Liver & Kidney)', 'Heart Institute', 'Neurosciences', 'Robotic Surgery', 'Oncology'],
      image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 161 6617111',
      receptionPhone: '+91 161 6617000',
      ambulancePhone: '+91 161 6617108',
      tpaDeskPhone: '+91 161 6617333',
      bloodBankPhone: '+91 161 6617222',
      category: 'Super-Speciality Corporate & Transplant',
      opdTimings: '24x7 Emergency • OPD 08:30 AM - 06:00 PM'
    },
    {
      id: 'hosp-21',
      name: 'Civil Hospital Sangrur',
      branch: 'Dhuri Road',
      network: 'Punjab Health Systems Corporation',
      city: 'sangrur',
      pincode: '148001',
      address: 'Dhuri Road, Near District Administrative Complex, Sangrur, Punjab 148001',
      accreditation: ['Government District Hospital', 'Ayushman Bharat'],
      beds: 200,
      rating: 4.5,
      reviewsCount: 2100,
      cashless: true,
      tpaPartners: ['Ayushman Bharat PMJAY', 'MDIndia', 'United India', 'Medi Assist'],
      specialties: ['Emergency Trauma Unit', 'Maternal & Child Health', 'General Medicine', 'Dialysis Center'],
      image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 1672 232000',
      receptionPhone: '+91 1672 232100',
      ambulancePhone: '+91 1672 232108',
      tpaDeskPhone: '+91 1672 232400',
      bloodBankPhone: '+91 1672 232222',
      category: 'Government District Hospital',
      opdTimings: '24x7 Casualty • OPD 08:00 AM - 02:00 PM'
    },
    {
      id: 'hosp-22',
      name: 'Amritsar Eye Clinic & Multi-Speciality Hospital',
      branch: 'Mall Road',
      network: 'Amritsar Healthcare Group',
      city: 'amritsar',
      pincode: '143001',
      address: 'Mall Road, Opp. Circuit House, Amritsar, Punjab 143001',
      accreditation: ['NABH', 'Ayushman Empaneled'],
      beds: 100,
      rating: 4.8,
      reviewsCount: 2600,
      cashless: true,
      tpaPartners: ['Medi Assist', 'Star Health', 'United India', 'HDFC ERGO', 'Ayushman Bharat'],
      specialties: ['Ophthalmology & Contoura LASIK', 'Retina & Glaucoma', 'ENT', 'General Surgery'],
      image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 183 2226000',
      receptionPhone: '+91 183 2226100',
      ambulancePhone: '+91 183 2226108',
      tpaDeskPhone: '+91 183 2226300',
      bloodBankPhone: '+91 183 2226222',
      category: 'Ophthalmology & Surgery Center',
      opdTimings: '24x7 Casualty • OPD 09:00 AM - 06:30 PM'
    },
    {
      id: 'hosp-23',
      name: 'Civil Hospital Kapurthala',
      branch: 'Circular Road',
      network: 'Punjab Health Systems Corporation',
      city: 'kapurthala',
      pincode: '144601',
      address: 'Circular Road, Near Shalimar Bagh, Kapurthala, Punjab 144601',
      accreditation: ['Government Hospital', 'Ayushman PMJAY'],
      beds: 180,
      rating: 4.5,
      reviewsCount: 1750,
      cashless: true,
      tpaPartners: ['Ayushman Bharat PMJAY', 'MDIndia', 'United India'],
      specialties: ['Casualty & Trauma Care', 'Orthopedics', 'Pediatrics', 'Obstetrics & Gynecology'],
      image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 1822 233000',
      receptionPhone: '+91 1822 233100',
      ambulancePhone: '+91 1822 233108',
      tpaDeskPhone: '+91 1822 233400',
      bloodBankPhone: '+91 1822 233222',
      category: 'Government District Hospital',
      opdTimings: '24x7 Casualty • OPD 08:00 AM - 02:00 PM'
    },
    {
      id: 'hosp-24',
      name: 'Homi Bhabha Cancer Hospital Sangrur',
      branch: 'Civil Hospital Campus',
      network: 'Tata Memorial Centre & Govt of Punjab',
      city: 'sangrur',
      pincode: '148001',
      address: 'Inside Civil Hospital Campus, Sangrur, Punjab 148001',
      accreditation: ['Tata Memorial Centre Unit', 'Government Cancer Centre', 'NABH'],
      beds: 100,
      rating: 4.9,
      reviewsCount: 3100,
      cashless: true,
      tpaPartners: ['Ayushman Bharat PMJAY', 'Chief Minister Cancer Relief Fund', 'Medi Assist', 'Star Health'],
      specialties: ['Medical Oncology', 'Radiation Oncology (Linear Accelerator)', 'Surgical Oncology', 'Palliative Care'],
      image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=600&q=80',
      emergencyPhone: '+91 1672 223999',
      receptionPhone: '+91 1672 223800',
      ambulancePhone: '+91 1672 223108',
      tpaDeskPhone: '+91 1672 223850',
      bloodBankPhone: '+91 1672 223830',
      category: 'Specialized Oncology & Radiotherapy',
      opdTimings: '24x7 Casualty • OPD 08:30 AM - 05:00 PM'
    }
  ],

  // Specialties
  specialties: [
    { id: 'gp', name: 'General Physician', icon: 'stethoscope', count: '140+ Doctors', desc: 'Fever, cough, infections, general wellness' },
    { id: 'gyn', name: 'Gynecology & Obstetrics', icon: 'heart', count: '95+ Doctors', desc: 'Periods, pregnancy, PCOS, fertility care' },
    { id: 'derm', name: 'Dermatology & Hair', icon: 'sparkles', count: '80+ Doctors', desc: 'Acne, skin allergy, hairfall, rashes' },
    { id: 'ped', name: 'Pediatrics & Child Care', icon: 'smile', count: '75+ Doctors', desc: 'Newborn care, vaccinations, child fever' },
    { id: 'card', name: 'Cardiology', icon: 'activity', count: '60+ Doctors', desc: 'Heart health, BP, chest pain, palpitations' },
    { id: 'ortho', name: 'Orthopedics & Joints', icon: 'shield', count: '70+ Doctors', desc: 'Back pain, arthritis, fractures, knee care' },
    { id: 'psych', name: 'Psychiatry & Therapy', icon: 'sun', count: '50+ Doctors', desc: 'Anxiety, depression, stress, sleep issues' },
    { id: 'gastro', name: 'Gastroenterology', icon: 'zap', count: '45+ Doctors', desc: 'Acid reflux, gas, liver health, digestion' },
    { id: 'diab', name: 'Diabetology & Endo', icon: 'target', count: '40+ Doctors', desc: 'Sugar control, thyroid, hormonal imbalance' },
    { id: 'ent', name: 'ENT Specialist', icon: 'mic', count: '35+ Doctors', desc: 'Ear pain, throat infection, sinus, hearing' },
    { id: 'eye', name: 'Ophthalmology', icon: 'eye', count: '40+ Doctors', desc: 'Eye strain, cataract, vision correction' },
    { id: 'dent', name: 'Dental Care', icon: 'check-circle', count: '55+ Doctors', desc: 'Toothache, cleaning, root canal, braces' }
  ],

  // Genuine Specialist Doctors with Verified Credentials in Punjab
  doctors: [
    {
      id: 'doc-1',
      name: 'Dr. Rajesh Sharma',
      qualification: 'MBBS, MD (Internal Medicine - DMC Ludhiana)',
      specialtyId: 'gp',
      specialty: 'Senior Consultant Physician',
      experience: 16,
      hospital: 'Dayanand Medical College & Hospital (DMCH)',
      city: 'ludhiana',
      nmcRegNo: 'PMC-48912',
      rating: 4.9,
      reviewsCount: 1420,
      fee: 650,
      goldFee: 0,
      languages: ['English', 'Punjabi', 'Hindi'],
      nextSlot: 'Today, within 15 mins',
      availableToday: true,
      avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80',
      about: 'Alumnus of DMC Ludhiana with 16+ years of clinical excellence in acute infection management, chronic lifestyle conditions, and preventive medicine.'
    },
    {
      id: 'doc-2',
      name: 'Dr. Gurpreet Kaur',
      qualification: 'MBBS, MS (OBG - GMC Amritsar), DNB, FICOG',
      specialtyId: 'gyn',
      specialty: 'Obstetrician & Gynecologist',
      experience: 19,
      hospital: 'Sri Guru Ram Das Institute of Medical Sciences (SGRD)',
      city: 'amritsar',
      nmcRegNo: 'PMC-32104',
      rating: 4.95,
      reviewsCount: 1840,
      fee: 800,
      goldFee: 0,
      languages: ['English', 'Punjabi', 'Hindi'],
      nextSlot: 'Today, 11:30 AM',
      availableToday: true,
      avatar: 'https://images.unsplash.com/photo-1594824813512-32b005e1975e?auto=format&fit=crop&w=300&q=80',
      about: 'Senior Consultant with extensive expertise in high-risk pregnancies, PCOS hormonal balancing, and minimally invasive laparoscopic gynecological care in Punjab.'
    },
    {
      id: 'doc-3',
      name: 'Dr. Arjun K. Rao',
      qualification: 'MBBS, MD (Dermatology - PGIMER Chandigarh)',
      specialtyId: 'derm',
      specialty: 'Dermatologist & Cosmetologist',
      experience: 12,
      hospital: 'Fortis Hospital Mohali',
      city: 'mohali',
      nmcRegNo: 'PMC-71239',
      rating: 4.88,
      reviewsCount: 980,
      fee: 700,
      goldFee: 0,
      languages: ['English', 'Punjabi', 'Hindi'],
      nextSlot: 'Today, within 20 mins',
      availableToday: true,
      avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=300&q=80',
      about: 'PGIMER trained specialist. Specializes in advanced clinical dermatology, acne scarring treatments, allergic dermatoses, and clinical trichology.'
    },
    {
      id: 'doc-4',
      name: 'Dr. Preeti Deshmukh',
      qualification: 'MBBS, MD (Pediatrics - GMC Patiala), IAP Fellow',
      specialtyId: 'ped',
      specialty: 'Senior Pediatrician & Neonatologist',
      experience: 15,
      hospital: 'Patel Hospital Jalandhar',
      city: 'jalandhar',
      nmcRegNo: 'PMC-65410',
      rating: 4.92,
      reviewsCount: 1610,
      fee: 750,
      goldFee: 0,
      languages: ['English', 'Punjabi', 'Hindi'],
      nextSlot: 'Today, 02:00 PM',
      availableToday: true,
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80',
      about: 'Compassionate pediatric care specialist focusing on infant development, childhood nutrition, respiratory allergies, and routine pediatric immunization.'
    },
    {
      id: 'doc-5',
      name: 'Dr. Sandeep Banerjee',
      qualification: 'MBBS, MD, DM (Cardiology - PGIMER Chandigarh)',
      specialtyId: 'card',
      specialty: 'Interventional Cardiologist',
      experience: 21,
      hospital: 'Max Super Speciality Hospital Bathinda',
      city: 'bathinda',
      nmcRegNo: 'PMC-41908',
      rating: 4.96,
      reviewsCount: 2200,
      fee: 1000,
      goldFee: 0,
      languages: ['English', 'Punjabi', 'Hindi'],
      nextSlot: 'Tomorrow, 10:00 AM',
      availableToday: false,
      avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=300&q=80',
      about: 'Pioneering cardiologist with 21+ years of experience across coronary angioplasty, heart failure therapies, and preventive cardiovascular screening.'
    },
    {
      id: 'doc-6',
      name: 'Dr. Amit Vashisht',
      qualification: 'MBBS, MS (Orthopedics - AIIMS New Delhi), MCh (Ortho - UK)',
      specialtyId: 'ortho',
      specialty: 'Senior Joint Replacement & Spine Surgeon',
      experience: 18,
      hospital: 'Government Medical College & Rajindra Hospital',
      city: 'patiala',
      nmcRegNo: 'PMC-52119',
      rating: 4.91,
      reviewsCount: 1340,
      fee: 900,
      goldFee: 0,
      languages: ['English', 'Hindi', 'Punjabi'],
      nextSlot: 'Today, 04:30 PM',
      availableToday: true,
      avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=300&q=80',
      about: 'Specialized in computer-navigated total knee and hip replacements, minimally invasive spine procedures, and complex sports ligament reconstruction.'
    },
    {
      id: 'doc-7',
      name: 'Dr. Sunita Nambiar',
      qualification: 'MBBS, MD (Psychiatry - CMC Ludhiana)',
      specialtyId: 'psych',
      specialty: 'Consultant Psychiatrist & Behavioral Therapist',
      experience: 14,
      hospital: 'Christian Medical College & Hospital (CMC)',
      city: 'ludhiana',
      nmcRegNo: 'PMC-89320',
      rating: 4.94,
      reviewsCount: 1120,
      fee: 850,
      goldFee: 0,
      languages: ['English', 'Punjabi', 'Hindi'],
      nextSlot: 'Today, within 30 mins',
      availableToday: true,
      avatar: 'https://images.unsplash.com/photo-1594824813512-32b005e1975e?auto=format&fit=crop&w=300&q=80',
      about: 'Trained at CMC Ludhiana. Compassionate expert in anxiety, clinical depression, work-life burnout, sleep disorders, and cognitive therapy.'
    },
    {
      id: 'doc-8',
      name: 'Dr. Harpreet Singh',
      qualification: 'MBBS, MD, DM (Gastroenterology - PGIMER Chandigarh)',
      specialtyId: 'gastro',
      specialty: 'Consultant Gastroenterologist & Hepatologist',
      experience: 13,
      hospital: 'Max Super Speciality Hospital Mohali',
      city: 'mohali',
      nmcRegNo: 'PMC-28491',
      rating: 4.89,
      reviewsCount: 890,
      fee: 850,
      goldFee: 0,
      languages: ['English', 'Punjabi', 'Hindi'],
      nextSlot: 'Today, 03:00 PM',
      availableToday: true,
      avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80',
      about: 'Expert in therapeutic endoscopy, fatty liver disease management, irritable bowel syndrome (IBS), gastroesophageal reflux, and pancreatitis.'
    }
  ],

  // Diagnostic Lab Tests & Health Packages (Matching NABL Standards like Metropolis & Dr Lal PathLabs)
  labPackages: [
    {
      id: 'pkg-1',
      name: 'Medroute Comprehensive Full Body Checkup',
      testsCount: 86,
      badge: 'Bestseller (Most Popular)',
      mrp: 4199,
      price: 1399,
      discount: '67% OFF',
      goldPrice: 1099,
      sampleType: 'Blood & Urine',
      fasting: '10-12 hours overnight fasting required',
      reportTime: 'Within 15 hours',
      partnerLab: 'Thyrocare Technologies / NABL & CAP Accredited',
      desc: 'Our most comprehensive preventive health package covering all vital organs: heart, liver, kidney, thyroid, blood sugar, bones, and complete blood counts.',
      parameters: [
        'Complete Blood Count (CBC with ESR - 24 parameters)',
        'Lipid Profile (Total Cholesterol, HDL, LDL, Triglycerides, VLDL - 8 parameters)',
        'Liver Function Test (SGOT, SGPT, Bilirubin Total/Direct, Alkaline Phosphatase, Protein - 11 parameters)',
        'Kidney Function Test (Serum Creatinine, Blood Urea Nitrogen, Uric Acid, Calcium - 6 parameters)',
        'Thyroid Profile Total (Total T3, Total T4, TSH - 3 parameters)',
        'Diabetic Screen (HbA1c Glycated Hemoglobin, Average Blood Glucose - 2 parameters)',
        'Vitamin Markers (Vitamin D3 25-Hydroxy & Vitamin B12 - 2 parameters)',
        'Urine Routine & Microscopic Examination (23 parameters)',
        'Iron Deficiency Profile (Serum Iron, TIBC, Transferrin Saturation - 4 parameters)',
        'Cardiac Risk Markers (hs-CRP, Homocysteine - 3 parameters)'
      ]
    },
    {
      id: 'pkg-2',
      name: 'Diabetic Care 360 & Cardiac Screen',
      testsCount: 52,
      badge: 'Specialized Chronic Care',
      mrp: 3200,
      price: 1199,
      discount: '62% OFF',
      goldPrice: 899,
      sampleType: 'Blood & Urine',
      fasting: '10-12 hours overnight fasting required',
      reportTime: 'Within 12 hours',
      partnerLab: 'Metropolis Healthcare / NABL Accredited',
      desc: 'Formulated by diabetologists to monitor long-term blood sugar trends, organ complications, diabetic nephropathy, and cardiovascular risks.',
      parameters: [
        'HbA1c (Glycosylated Hemoglobin) with Estimated Average Glucose',
        'Fasting Blood Sugar (Glucose Fasting)',
        'Lipid Profile Comprehensive (Cholesterol, Triglycerides, HDL, LDL, Ratio)',
        'Kidney Function & Microalbuminuria (Urine Microalbumin/Creatinine Ratio)',
        'Complete Hemogram (CBC - 24 parameters)',
        'Serum Creatinine & eGFR (Estimated Glomerular Filtration Rate)',
        'Serum Electrolytes (Sodium, Potassium, Chloride)'
      ]
    },
    {
      id: 'pkg-3',
      name: 'Women’s Advanced Wellness & Hormonal Profile',
      testsCount: 68,
      badge: 'Specially for Women',
      mrp: 3800,
      price: 1499,
      discount: '60% OFF',
      goldPrice: 1199,
      sampleType: 'Blood & Urine',
      fasting: '10-12 hours fasting required',
      reportTime: 'Within 18 hours',
      partnerLab: 'Dr. Lal PathLabs / NABL Accredited',
      desc: 'Customized for female wellness covering thyroid, anemia markers, hormonal balance, bone density vitamins, and PCOS risk indicators.',
      parameters: [
        'Thyroid Profile Complete (Free T3, Free T4, Ultrasensitive TSH)',
        'Anemia & Iron Profile (Serum Ferritin, Iron, Total Iron Binding Capacity)',
        'Vitamin D3 (25-OH) & Vitamin B12',
        'Complete Blood Count (CBC - 24 tests)',
        'Calcium & Serum Phosphorus',
        'Liver & Kidney Health Screens',
        'HbA1c & Fasting Blood Sugar'
      ]
    },
    {
      id: 'pkg-4',
      name: 'Senior Citizen Vital Care (Male/Female)',
      testsCount: 75,
      badge: 'Age 50+ Recommended',
      mrp: 4500,
      price: 1699,
      discount: '62% OFF',
      goldPrice: 1399,
      sampleType: 'Blood & Urine',
      fasting: '10-12 hours fasting required',
      reportTime: 'Within 16 hours',
      partnerLab: 'Thyrocare / NABL & CAP Accredited',
      desc: 'Designed for elders to assess cardiac load, joint health, uric acid, kidney filtration, cognitive vitamin markers, and prostate/hormonal safety.',
      parameters: [
        'Comprehensive Lipid & Cardiac Risk Profile',
        'Renal / Kidney Health (BUN, Creatinine, Uric Acid, eGFR)',
        'Bone & Joint Screen (Calcium, Alkaline Phosphatase, Uric Acid)',
        'Liver Function & Protein Profile',
        'HbA1c & Blood Glucose',
        'Vitamin D3 & Vitamin B12',
        'Thyroid TSH Screen',
        'Complete Blood Count & Urine Routine'
      ]
    }
  ],

  // Individual Popular Diagnostic Tests
  individualTests: [
    { id: 't-1', name: 'HbA1c (Glycated Hemoglobin)', mrp: 600, price: 299, sample: 'Blood', fasting: 'Non-fasting', turnaround: '6 hrs' },
    { id: 't-2', name: 'Thyroid Profile Total (T3, T4, TSH)', mrp: 550, price: 249, sample: 'Blood', fasting: 'Non-fasting', turnaround: '8 hrs' },
    { id: 't-3', name: 'Complete Blood Count (CBC - 24 params)', mrp: 450, price: 199, sample: 'Blood', fasting: 'Non-fasting', turnaround: '4 hrs' },
    { id: 't-4', name: 'Vitamin D3 (25-Hydroxy)', mrp: 1200, price: 499, sample: 'Blood', fasting: 'Non-fasting', turnaround: '12 hrs' },
    { id: 't-5', name: 'Vitamin B12 (Cyanocobalamin)', mrp: 1100, price: 479, sample: 'Blood', fasting: 'Non-fasting', turnaround: '12 hrs' },
    { id: 't-6', name: 'Lipid Profile Comprehensive', mrp: 750, price: 349, sample: 'Blood', fasting: '10-12 hrs fasting', turnaround: '6 hrs' },
    { id: 't-7', name: 'Liver Function Test (LFT)', mrp: 800, price: 349, sample: 'Blood', fasting: '8 hrs fasting', turnaround: '6 hrs' },
    { id: 't-8', name: 'Kidney Function Test (KFT with Electrolytes)', mrp: 850, price: 379, sample: 'Blood', fasting: 'Non-fasting', turnaround: '6 hrs' }
  ],

  // Genuine Medicines Catalog (Authentic Composition & Brands)
  medicines: [
    {
      id: 'med-1',
      name: 'Telma 40mg Tablet',
      generic: 'Telmisartan (40mg)',
      manufacturer: 'Glenmark Pharmaceuticals Ltd',
      category: 'Blood Pressure / Cardiac',
      stripSize: 'Strip of 30 tablets',
      mrp: 298,
      price: 238,
      discount: '20% OFF',
      rxRequired: true,
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
      desc: 'Used in the management of hypertension (high blood pressure) and prevention of cardiovascular events.'
    },
    {
      id: 'med-2',
      name: 'Glycomet-GP 1 Tablet',
      generic: 'Glimepiride (1mg) + Metformin Hydrochloride (500mg)',
      manufacturer: 'USV Ltd',
      category: 'Diabetes Care',
      stripSize: 'Strip of 15 tablets',
      mrp: 145,
      price: 116,
      discount: '20% OFF',
      rxRequired: true,
      image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=300&q=80',
      desc: 'Dual-action medication for effective glycemic control in adults with type 2 diabetes mellitus.'
    },
    {
      id: 'med-3',
      name: 'Thyronorm 50mcg Tablet',
      generic: 'Thyroxine Sodium (50mcg)',
      manufacturer: 'Abbott Healthcare Pvt Ltd',
      category: 'Thyroid / Hormones',
      stripSize: 'Bottle of 120 tablets',
      mrp: 215,
      price: 172,
      discount: '20% OFF',
      rxRequired: true,
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
      desc: 'Synthetic thyroid hormone prescribed for the treatment of hypothyroidism (underactive thyroid gland).'
    },
    {
      id: 'med-4',
      name: 'Atorva 10mg Tablet',
      generic: 'Atorvastatin (10mg)',
      manufacturer: 'Zydus Cadila',
      category: 'Blood Pressure / Cardiac',
      stripSize: 'Strip of 15 tablets',
      mrp: 168,
      price: 134,
      discount: '20% OFF',
      rxRequired: true,
      image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=300&q=80',
      desc: 'Statins used to lower bad cholesterol (LDL) and triglycerides in the bloodstream.'
    },
    {
      id: 'med-5',
      name: 'Augmentin 625 Duo Tablet',
      generic: 'Amoxicillin (500mg) + Clavulanic Acid (125mg)',
      manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
      category: 'Antibiotics',
      stripSize: 'Strip of 10 tablets',
      mrp: 223,
      price: 178,
      discount: '20% OFF',
      rxRequired: true,
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
      desc: 'Broad-spectrum penicillin antibiotic combined with a beta-lactamase inhibitor for bacterial infections.'
    },
    {
      id: 'med-6',
      name: 'Pan-D Capsule',
      generic: 'Pantoprazole (40mg) + Domperidone (30mg SR)',
      manufacturer: 'Alkem Laboratories Ltd',
      category: 'Gastroenterology',
      stripSize: 'Strip of 15 capsules',
      mrp: 199,
      price: 159,
      discount: '20% OFF',
      rxRequired: true,
      image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=300&q=80',
      desc: 'Effective relief for acid reflux, gastroesophageal reflux disease (GERD), and acidity nausea.'
    },
    {
      id: 'med-7',
      name: 'Dolo 650 Tablet',
      generic: 'Paracetamol (650mg)',
      manufacturer: 'Micro Labs Ltd',
      category: 'Pain Relief & Fever',
      stripSize: 'Strip of 15 tablets',
      mrp: 34,
      price: 29,
      discount: '15% OFF',
      rxRequired: false,
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
      desc: 'India’s trusted antipyretic and analgesic for rapid relief from high fever, headaches, and body pain.'
    },
    {
      id: 'med-8',
      name: 'Shelcal 500 Tablet',
      generic: 'Calcium (500mg) + Vitamin D3 (250 IU)',
      manufacturer: 'Torrent Pharmaceuticals Ltd',
      category: 'Vitamins & Supplements',
      stripSize: 'Strip of 15 tablets',
      mrp: 131,
      price: 105,
      discount: '20% OFF',
      rxRequired: false,
      image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=300&q=80',
      desc: 'Vital mineral formulation for strengthening bone mineral density and preventing osteoporosis.'
    },
    {
      id: 'med-9',
      name: 'Becosules Z Capsule',
      generic: 'B-Complex Vitamins + Vitamin C + Zinc',
      manufacturer: 'Pfizer Ltd',
      category: 'Vitamins & Supplements',
      stripSize: 'Strip of 20 capsules',
      mrp: 54,
      price: 46,
      discount: '15% OFF',
      rxRequired: false,
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
      desc: 'Therapeutic multivitamin supplement for immune vitality, skin health, and mouth ulcer recovery.'
    },
    {
      id: 'med-10',
      name: 'Otrivin Oxy Fast Relief Nasal Spray',
      generic: 'Oxymetazoline Hydrochloride (0.05% w/v)',
      manufacturer: 'GlaxoSmithKline Consumer Healthcare',
      category: 'Cold & Cough',
      stripSize: 'Bottle of 10ml',
      mrp: 110,
      price: 93,
      discount: '15% OFF',
      rxRequired: false,
      image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=300&q=80',
      desc: 'Acts in 25 seconds to open blocked nasal passages during sinus and viral colds.'
    }
  ],

  // Genuine Surgical Procedures with Accurate Clinical Specs
  surgeries: [
    {
      id: 'surg-1',
      name: 'Cataract Eye Surgery',
      clinicalTerm: 'Phacoemulsification with Foldable Monofocal/Multifocal IOL',
      category: 'Ophthalmology',
      anesthesia: 'Topical / Local Drop Anesthesia (Pain-free)',
      duration: '15 - 25 Minutes',
      hospitalStay: 'Day Care (Discharge in 2-3 hours)',
      recoveryTime: 'Normal vision resume in 24 - 48 hours',
      avgCost: 35000,
      costRange: '₹25,000 - ₹55,000',
      monthlyEmi: 2916,
      cashlessEligible: true,
      desc: 'Micro-incision blade-free ultrasound surgery to remove cloudy natural lens and implant US-FDA approved intraocular lens.',
      inclusions: [
        'Dedicated Medroute Care Buddy concierge',
        'Free pre-surgery optical biometry assessment',
        '100% Cashless insurance approval assistance',
        'Free post-surgery drop medication kit & 3 follow-up consultations'
      ]
    },
    {
      id: 'surg-2',
      name: 'Gallbladder Stone Removal',
      clinicalTerm: 'Laparoscopic Cholecystectomy (3D Minimal Access)',
      category: 'General & Laparoscopic Surgery',
      anesthesia: 'General Anesthesia',
      duration: '40 - 55 Minutes',
      hospitalStay: '24 Hours (Overnight Stay)',
      recoveryTime: 'Desk work in 3-5 days; Full recovery in 10 days',
      avgCost: 65000,
      costRange: '₹55,000 - ₹90,000',
      monthlyEmi: 5416,
      cashlessEligible: true,
      desc: 'Gold standard 3D keyhole surgery with 3 tiny incisions to excise inflamed gallbladder with gallstones.',
      inclusions: [
        'Free second opinion from Senior Laparoscopic Surgeon',
        'TPA Pre-authorization desk handling all claim paperwork',
        'Complimentary private room upgrade assistance',
        'Post-operative clinical dietitian diet plan'
      ]
    },
    {
      id: 'surg-3',
      name: 'Hernia Repair Surgery',
      clinicalTerm: 'Laparoscopic Inguinal / Umbilical Hernioplasty with 3D Mesh',
      category: 'General & Laparoscopic Surgery',
      anesthesia: 'Spinal or General Anesthesia',
      duration: '45 - 60 Minutes',
      hospitalStay: 'Day Care to 24 Hours',
      recoveryTime: 'Walk same day; light activity in 5 days',
      avgCost: 58000,
      costRange: '₹48,000 - ₹82,000',
      monthlyEmi: 4833,
      cashlessEligible: true,
      desc: 'Minimally invasive repair reinforcing the abdominal wall defect with high-grade biocompatible dual-surface mesh.',
      inclusions: [
        'Care Buddy bedside concierge support',
        'Cashless coverage under corporate & retail health policies',
        'Zero-Cost EMI up to 12 months tenure'
      ]
    },
    {
      id: 'surg-4',
      name: 'Total Knee Replacement (TKR)',
      clinicalTerm: 'Computer-Navigated Bilateral/Unilateral Knee Arthroplasty',
      category: 'Orthopedics',
      anesthesia: 'Combined Spinal-Epidural (CSE)',
      duration: '75 - 90 Minutes per knee',
      hospitalStay: '3 - 4 Days',
      recoveryTime: 'Walking with support on Day 2; Independent walking in 3 weeks',
      avgCost: 175000,
      costRange: '₹1,40,000 - ₹2,40,000',
      monthlyEmi: 14583,
      cashlessEligible: true,
      desc: 'Precision joint replacement utilizing world-class US implants (Stryker / Zimmer Biomet) for severe osteoarthritis relief.',
      inclusions: [
        'Complete insurance documentation & room tariff coordination',
        'In-hospital physiotherapy rehabilitation sessions',
        'Complimentary 1-month home physiotherapy guidance'
      ]
    },
    {
      id: 'surg-5',
      name: 'Piles & Anorectal Surgery',
      clinicalTerm: 'Minimally Invasive Diode Laser Hemorrhoidoplasty (LHP)',
      category: 'Proctology',
      anesthesia: 'Short General / Spinal Anesthesia',
      duration: '25 - 30 Minutes',
      hospitalStay: 'Day Care (Discharge same evening)',
      recoveryTime: 'Zero cuts, zero bleeding; Back to routine in 48 hours',
      avgCost: 45000,
      costRange: '₹38,000 - ₹62,000',
      monthlyEmi: 3750,
      cashlessEligible: true,
      desc: 'Advanced 1470nm diode laser beam precisely shrinks hemorrhoidal cushions without painful surgical incisions.',
      inclusions: [
        '100% Confidential proctology consultation',
        'Cashless admission in NABH-certified surgical centers',
        'Care Buddy assisted hassle-free discharge'
      ]
    },
    {
      id: 'surg-6',
      name: 'Kidney Stone Laser Removal',
      clinicalTerm: 'RIRS (Retrograde Intrarenal Surgery) with Holmium Laser',
      category: 'Urology',
      anesthesia: 'General / Spinal Anesthesia',
      duration: '40 - 60 Minutes',
      hospitalStay: '24 Hours',
      recoveryTime: 'Normal routine resumed in 2-3 days',
      avgCost: 72000,
      costRange: '₹60,000 - ₹95,000',
      monthlyEmi: 6000,
      cashlessEligible: true,
      desc: 'Flexible ureterorenoscopy delivering laser energy directly into the renal pelvis to pulverize stones to dust without external scars.',
      inclusions: [
        'Laser lithotripsy by senior board-certified urologist',
        'Pre-authorization paperwork completed within 60 minutes',
        'Follow-up ultrasound and stent removal package included'
      ]
    },
    {
      id: 'surg-7',
      name: 'LASIK Eye Vision Correction',
      clinicalTerm: 'Blade-Free Contoura Vision / SMILE Laser Eye Surgery',
      category: 'Ophthalmology',
      anesthesia: 'Anesthetic Eye Drops (Zero needles)',
      duration: '10 - 15 Minutes both eyes',
      hospitalStay: 'Day Care (Discharge in 1 hour)',
      recoveryTime: 'Clear HD vision within 24 hours',
      avgCost: 55000,
      costRange: '₹45,000 - ₹85,000',
      monthlyEmi: 4583,
      cashlessEligible: false,
      desc: 'Topography-guided custom corneal reshaping for permanent freedom from spectacles and contact lenses.',
      inclusions: [
        'Comprehensive 18-parameter corneal suitability checkup',
        'Zero-Cost EMI starting from ₹3,750/month',
        '1-year unlimited post-LASIK ophthalmology visits'
      ]
    },
    {
      id: 'surg-8',
      name: 'Varicose Veins Laser Therapy',
      clinicalTerm: 'EVLT (Endovenous Laser Treatment) + Sclerotherapy',
      category: 'Vascular Surgery',
      anesthesia: 'Tumescent Local Anesthesia',
      duration: '45 Minutes',
      hospitalStay: 'Day Care (Walk out within 3 hours)',
      recoveryTime: 'Immediate walking; No bed rest needed',
      avgCost: 68000,
      costRange: '₹55,000 - ₹90,000',
      monthlyEmi: 5666,
      cashlessEligible: true,
      desc: 'Catheter-guided laser energy seals faulty leg vein valves, ending pain, swelling, and ulcer risks.',
      inclusions: [
        'Free color doppler venous mapping scan',
        'Full medical insurance cashless support',
        'Class-II medical compression stockings provided'
      ]
    }
  ],

  // Medroute Gold Membership Tiers (MediBuddy Gold equivalent)
  goldPlans: [
    {
      id: 'gold-quarterly',
      name: '3 Months Starter',
      period: '3 Months',
      mrp: 999,
      price: 499,
      discount: '50% OFF',
      familyMembers: 4,
      desc: 'Great for trying out unlimited 24/7 teleconsultations for your immediate family.'
    },
    {
      id: 'gold-annual',
      name: '1 Year Family Care',
      period: '12 Months',
      popular: true,
      mrp: 2499,
      price: 999,
      discount: '60% OFF',
      familyMembers: 6,
      desc: 'Our most loved plan. Complete year-round healthcare safety net for up to 6 members.'
    },
    {
      id: 'gold-platinum',
      name: '1 Year Platinum Care',
      period: '12 Months',
      mrp: 3999,
      price: 1799,
      discount: '55% OFF',
      familyMembers: 6,
      includesFreeTest: true,
      desc: 'Includes 1 FREE Comprehensive Full Body Health Checkup (worth ₹1,399) + Unlimited consults.'
    }
  ],

  // Live Claim Sample for Real-Time Tracker
  sampleClaims: {
    'MED-78291': {
      claimId: 'MED-78291',
      patientName: 'Sunita Sharma',
      age: 48,
      policyNumber: 'NIC-RET-8849201',
      tpa: 'Medi Assist Insurance TPA Pvt Ltd',
      hospital: 'Fortis Hospital Mohali, SAS Nagar, Punjab',
      treatment: 'Laparoscopic Cholecystectomy',
      admissionDate: '21 Sep 2026',
      estimatedAmount: '₹82,500',
      approvedAmount: '₹80,000',
      currentStep: 3, // 1: Submitted, 2: Under Review, 3: Pre-Auth Approved, 4: Hospitalized, 5: Settled
      statusText: 'Cashless Pre-Authorization Approved',
      statusType: 'success',
      steps: [
        { title: 'Claim Intimation & KYC Submitted', time: '21 Sep 2026, 09:15 AM', done: true },
        { title: 'TPA Document Verification', time: '21 Sep 2026, 10:45 AM', done: true },
        { title: 'Cashless Pre-Authorization Issued (₹80,000)', time: '21 Sep 2026, 12:20 PM', done: true },
        { title: 'Hospital Admission & Surgery in Progress', time: 'In Progress', active: true },
        { title: 'Final Discharge & Direct Settlement', time: 'Pending Discharge', done: false }
      ]
    },
    'MED-44120': {
      claimId: 'MED-44120',
      patientName: 'Rahul Verma',
      age: 34,
      policyNumber: 'HDFC-CORP-33918',
      tpa: 'Medi Assist Insurance TPA Pvt Ltd',
      hospital: 'Christian Medical College & Hospital (CMC), Ludhiana, Punjab',
      treatment: 'Arthroscopic ACL Reconstruction',
      admissionDate: '18 Sep 2026',
      estimatedAmount: '₹1,15,000',
      approvedAmount: '₹1,15,000',
      currentStep: 5,
      statusText: 'Claim Settled 100% Cashless',
      statusType: 'success',
      steps: [
        { title: 'Claim Intimation & KYC Submitted', time: '18 Sep 2026, 08:30 AM', done: true },
        { title: 'TPA Document Verification', time: '18 Sep 2026, 09:40 AM', done: true },
        { title: 'Cashless Pre-Authorization Issued (₹1,15,000)', time: '18 Sep 2026, 11:15 AM', done: true },
        { title: 'Patient Admitted & Discharged', time: '19 Sep 2026, 04:00 PM', done: true },
        { title: 'Final Hospital Settlement Completed', time: '20 Sep 2026, 11:30 AM', done: true }
      ]
    }
  },

  // AI Clinical Triage - Symptom Checker Categories
  aiSymptoms: [
    {
      category: 'Common Infections & Fever',
      symptoms: ['High Fever & Chills', 'Persistent Dry Cough', 'Sore Throat', 'Fatigue & Body Ache'],
      recommendedSpecialty: 'General Physician',
      specialtyId: 'gp',
      recommendedDoctor: 'Dr. Rajesh Sharma (AIIMS Alumnus)',
      recommendedTest: 'Complete Blood Count (CBC) + ESR',
      advice: 'Drink warm fluids, monitor your temperature every 4 hours, and avoid self-medicating with antibiotics without a prescription.'
    },
    {
      category: 'Digestive & Stomach Issues',
      symptoms: ['Burning Sensation in Chest (Acidity)', 'Severe Abdominal Cramps', 'Nausea / Vomiting', 'Gas & Chronic Bloating'],
      recommendedSpecialty: 'Gastroenterology',
      specialtyId: 'gastro',
      recommendedDoctor: 'Dr. Vivek Singhal',
      recommendedTest: 'Liver Function Test (LFT) & Abdominal Ultrasound',
      advice: 'Avoid spicy, greasy meals and carbonated drinks. Eat small, frequent bland meals and remain upright for 2 hours after food.'
    },
    {
      category: 'Skin, Scalp & Hair',
      symptoms: ['Severe Acne & Breakouts', 'Itchy Red Rash or Hives', 'Rapid Hair Thinning', 'Fungal Infection / Ringworm'],
      recommendedSpecialty: 'Dermatology & Hair',
      specialtyId: 'derm',
      recommendedDoctor: 'Dr. Arjun K. Rao (Gold Medalist)',
      recommendedTest: 'Thyroid Profile Total & Serum Ferritin',
      advice: 'Avoid scratching the affected area to prevent bacterial secondary infection. Do not apply strong steroid creams without consulting.'
    },
    {
      category: 'Bone, Joint & Back Pain',
      symptoms: ['Knee Pain when Walking/Stairs', 'Lower Back Stiffness', 'Shoulder Joint Immobility', 'Morning Joint Swelling'],
      recommendedSpecialty: 'Orthopedics & Joints',
      specialtyId: 'ortho',
      recommendedDoctor: 'Dr. Amit Vashisht (AIIMS Specialist)',
      recommendedTest: 'Serum Uric Acid, Calcium & Vitamin D3',
      advice: 'Apply warm or cold compress for 15 minutes. Avoid heavy lifting and floor cross-legged sitting until evaluated.'
    },
    {
      category: 'Women’s Health & Hormones',
      symptoms: ['Irregular or Painful Periods', 'PCOS Weight Gain', 'Pregnancy Confirmation', 'Pelvic Discomfort'],
      recommendedSpecialty: 'Gynecology & Obstetrics',
      specialtyId: 'gyn',
      recommendedDoctor: 'Dr. Meenakshi Sundaram (CMC Vellore / FRCOG)',
      recommendedTest: 'Women’s Advanced Hormonal & Wellness Profile',
      advice: 'Keep a record of your menstrual cycle dates and symptoms. Stay well hydrated and maintain consistent sleep patterns.'
    },
    {
      category: 'Cardiovascular & Vital Warning',
      symptoms: ['Chest Pain / Tightness radiating to Left Arm', 'Sudden Shortness of Breath', 'Palpitations & Extreme Dizziness'],
      recommendedSpecialty: 'Cardiology (Emergency Evaluation)',
      specialtyId: 'card',
      recommendedDoctor: 'Dr. Sandeep Banerjee (PGIMER Chandigarh)',
      recommendedTest: 'Lipid Profile Comprehensive, ECG & Troponin-I',
      advice: 'CRITICAL: If you experience crushing chest pain with breathlessness or sweating, seek emergency medical care at the nearest hospital immediately.'
    }
  ],

  // Vaccination Schedule Database (Birth, Infant & Adult Immunization)
  vaccines: {
    birth: [
      { name: "BCG", protection: "Tuberculosis", route: "Intradermal", mandatory: true },
      { name: "Hepatitis B (Birth Dose)", protection: "Hepatitis B viral infection", route: "Intramuscular", mandatory: true },
      { name: "Oral Polio Vaccine (OPV 0)", protection: "Polio Virus", route: "Oral drops", mandatory: true }
    ],
    "6weeks": [
      { name: "DTwP / DTaP 1", protection: "Diphtheria, Tetanus, Pertussis", route: "Intramuscular", mandatory: true },
      { name: "IPV 1", protection: "Inactivated Polio", route: "Intramuscular", mandatory: true },
      { name: "Hepatitis B 1", protection: "Hepatitis B", route: "Intramuscular", mandatory: true },
      { name: "Hib 1", protection: "Haemophilus influenzae type b", route: "Intramuscular", mandatory: true },
      { name: "Rotavirus 1", protection: "Severe childhood diarrhea", route: "Oral drops", mandatory: true },
      { name: "PCV 1", protection: "Pneumococcal pneumonia / meningitis", route: "Intramuscular", mandatory: true }
    ],
    "6months": [
      { name: "Influenza (Flu) Annual 1", protection: "Seasonal Influenza virus", route: "Intramuscular", mandatory: false },
      { name: "Typhoid Conjugate Vaccine", protection: "Typhoid Fever", route: "Intramuscular", mandatory: true }
    ],
    "9months": [
      { name: "MMR 1", protection: "Measles, Mumps, Rubella", route: "Subcutaneous", mandatory: true },
      { name: "Meningococcal (Optional)", protection: "Meningococcal meningitis", route: "Intramuscular", mandatory: false }
    ],
    "12-15months": [
      { name: "Varicella 1 (Chickenpox)", protection: "Varicella zoster virus", route: "Subcutaneous", mandatory: true },
      { name: "Hepatitis A 1", protection: "Hepatitis A viral liver infection", route: "Intramuscular", mandatory: true },
      { name: "MMR Booster 2", protection: "Measles, Mumps, Rubella", route: "Subcutaneous", mandatory: true }
    ],
    adult: [
      { name: "Annual Quadrivalent Flu", protection: "Current Influenza strains", route: "Annual single dose", mandatory: true },
      { name: "Td / Tdap Booster", protection: "Tetanus, Diphtheria, Pertussis", route: "Every 10 years", mandatory: true },
      { name: "HPV (Human Papillomavirus)", protection: "Cervical & anogenital cancers", route: "Up to age 45 (2 or 3 doses)", mandatory: true },
      { name: "Shingles (Zoster Vaccine)", protection: "Herpes Zoster nerve neuralgia", route: "Recommended for adults 50+", mandatory: true },
      { name: "Pneumococcal (Prevnar 20)", protection: "Bacterial pneumonia & sepsis", route: "Recommended for adults 65+ or chronic conditions", mandatory: true }
    ]
  },

  // Default User State - Seed data for the reactive store (localStorage fallback)
  defaultState: {
    selectedCity: 'ludhiana',
    user: {
      isLoggedIn: true,
      name: 'Arun Kumar',
      phone: '+91 98450 12345',
      email: 'arun.kumar@example.com',
      isGoldMember: false,
      goldPlan: null,
      corporateWalletBalance: 12500
    },
    cart: [
      {
        id: 'pkg-1',
        type: 'lab',
        name: 'Medroute Comprehensive Full Body Checkup (86 Tests)',
        price: 1399,
        goldPrice: 1099,
        qty: 1,
        image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=300&q=80'
      }
    ],
    bookings: [
      {
        id: 'APT-10928',
        doctorId: 'doc-1',
        doctorName: 'Dr. Rajesh Sharma',
        specialty: 'Senior Consultant Physician',
        date: 'Today, 23 Sep 2026',
        time: '11:00 AM',
        type: 'Video Consultation',
        fee: 0,
        status: 'Confirmed',
        symptoms: 'Mild throat irritation and seasonal fever',
        link: '#'
      }
    ],
    orders: [
      {
        id: 'ORD-98210',
        items: ['Telma 40mg Tablet x 1', 'Becosules Z Capsule x 1'],
        total: 284,
        status: 'Out for Delivery',
        expected: 'Today by 2:00 PM',
        address: '42, Model Town, Near Gulati Chowk, Ludhiana, Punjab - 141002'
      }
    ],
    activeClaim: 'MED-78291',
    appliedCoupon: null
  }
};
